import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {
  REPORT_SCHEMA,
  buildDeveloperCardReportV1,
  encodePublicReport,
  decodePublicReport,
  encodeCompactShareReport,
  decodeCompactShareReport,
  buildPublicReportUrl,
  buildMachineReportUrl,
  serializeMachineReport,
  readPublicReportFromLocation
} from '../src/public-report.mjs';

test('DeveloperCardReport v1 is canonical, public-safe and machine-readable', () => {
  const payload = {
    v:1,
    handle:'アルティメット',
    type:'システム構築型',
    recommended:[{name:'public-one',reason:'showcase'}],
    detail:{
      axes:[['活動量',80]],
      recommended:[{name:'public-one',reason:'showcase'},{name:'hidden-one',reason:'must not leak'}]
    },
    excluded_repo_names:['secret-repo'],
    arbitrary_private_field:'never serialize me'
  };
  const report = buildDeveloperCardReportV1(payload);
  assert.equal(report.schema, REPORT_SCHEMA);
  assert.equal(report.schema_version, 1);
  assert.equal(report.public_safe, true);
  assert.equal(report.evidence_scope, 'public-safe-aggregate');
  assert.equal(report.detail.recommended.length, 1);
  assert.equal(report.detail.recommended[0].name, 'public-one');
  assert.equal('excluded_repo_names' in report, false);
  assert.equal('arbitrary_private_field' in report, false);

  const token = encodePublicReport(payload);
  assert.deepEqual(decodePublicReport(token), report);
  assert.deepEqual(JSON.parse(serializeMachineReport(payload)), report);
});

test('human share URLs use compact transport while machine URLs keep canonical report transport', () => {
  const payload = realisticPayload();
  const human = new URL(buildPublicReportUrl(payload, 'https://example.com/Developer-Card/?old=1#x'));
  assert.ok(human.searchParams.get('r'));
  assert.equal(human.searchParams.get('report'), null);
  assert.equal(human.searchParams.get('old'), null);
  assert.equal(human.hash, '');
  assert.equal(human.searchParams.get('view'), null);
  assert.ok(human.toString().length < 2800, `compact human URL too long: ${human.toString().length}`);

  const compact = decodeCompactShareReport(encodeCompactShareReport(payload));
  assert.equal(compact.handle, 'ultimate');
  assert.equal(compact.evidence_count, 26);
  assert.equal(compact.evidence_coverage, 100);
  assert.equal(compact.detail.recommended.length, 3);
  assert.deepEqual(compact.detail.evidence.signatures.slice(0,3), ['GitHub Actions','Python package','FastAPI/Python API']);

  const fromLocation = readPublicReportFromLocation({search:human.search,hash:''});
  assert.equal(fromLocation.type, '横断オーケストレーター型');
  assert.equal(fromLocation.detail.evidence.repos_with_tests, 13);

  const machine = new URL(buildMachineReportUrl(payload, 'https://example.com/Developer-Card/'));
  assert.ok(machine.searchParams.get('report'));
  assert.equal(machine.searchParams.get('r'), null);
  assert.equal(machine.searchParams.get('view'), 'json');

  const legacyToken = encodePublicReport(payload);
  const legacy = readPublicReportFromLocation({search:'',hash:`#report=${legacyToken}`});
  assert.equal(legacy.handle, 'ultimate');
});

test('compact public transport remains allow-list based', () => {
  const payload = realisticPayload();
  payload.excluded_repo_names = ['private-secret'];
  payload.detail.raw_tree = ['secret/path'];
  const compact = decodeCompactShareReport(encodeCompactShareReport(payload));
  const serialized = JSON.stringify(compact);
  assert.doesNotMatch(serialized, /private-secret/);
  assert.doesNotMatch(serialized, /secret\/path/);
});

test('canonical X-card preview and PNG export use the same renderer contract', async () => {
  const app = await readFile(new URL('../src/app.mjs', import.meta.url), 'utf8');
  const share = await readFile(new URL('../src/share-card.mjs', import.meta.url), 'utf8');
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  assert.match(app, /renderShareCardDom\(lastCardModel\)/);
  assert.match(app, /exportShareCardPng\(lastCardModel\)/);
  assert.doesNotMatch(app, /function renderPngCard/);
  assert.match(share, /GitHub解析でわかる/);
  assert.match(share, /開発スタイル診断/);
  assert.match(share, /詳細レポートはこちら/);
  assert.match(html, /id="detailQr"/);
});

test('QR is generated by browser-compatible runtime with maximum FV capacity', async () => {
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  const share = await readFile(new URL('../src/share-card.mjs', import.meta.url), 'utf8');
  assert.match(html, /qrcodejs\/1\.0\.0\/qrcode\.min\.js/);
  assert.match(share, /globalThis\.QRCode/);
  assert.match(share, /CorrectLevel\.L/);
  assert.match(share, /toDataURL\('image\/png'\)/);
  assert.doesNotMatch(share, /svgFallback\('DETAIL'\)/);
});

test('QR failure cannot suppress the diagnostic result card', async () => {
  const share = await readFile(new URL('../src/share-card.mjs', import.meta.url), 'utf8');
  assert.match(share, /let qrDataUrl = ''/);
  assert.match(share, /try \{\s*qrDataUrl = await makeQr\(detailUrl\);\s*\} catch/);
  assert.match(share, /qr_error: qrError/);
  assert.match(share, /QR生成失敗/);
});

test('share and machine actions have separate responsibilities', async () => {
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  const app = await readFile(new URL('../src/app.mjs', import.meta.url), 'utf8');
  assert.match(html, /id="download">Xカードを保存/);
  assert.match(html, /id="share">投稿文をコピー/);
  assert.match(html, /id="machineDownload">JSONレポートを保存/);
  assert.match(html, /id="machineCopy">Machine URLをコピー/);
  assert.match(app, /navigator\.canShare\?\.\(\{files:\[file\]\}\)/);
  assert.match(app, /copyText\(text\)/);
  assert.match(app, /serializeMachineReport\(lastCardModel\.publicPayload\)/);
  assert.match(app, /copyText\(lastCardModel\.machine_url\)/);
});

test('machine view renders canonical JSON after browser-side decode', async () => {
  const detail = await readFile(new URL('../src/detail-report.mjs', import.meta.url), 'utf8');
  assert.match(detail, /isMachineReportLocation\(\)/);
  assert.match(detail, /id="machineReport"/);
  assert.match(detail, /serializeMachineReport\(payload\)/);
});

test('avatar preprocessing can remove only edge-connected light backgrounds', async () => {
  const guard = await readFile(new URL('../src/mobile-memory-guard.mjs', import.meta.url), 'utf8');
  assert.match(guard, /removeConnectedLightBackground/);
  assert.match(guard, /lightBorder\/border<0\.55/);
  assert.match(guard, /d\[p\+3\]=0/);
});

function realisticPayload() {
  return {
    handle:'ultimate', github_user:'nobutakayamauchi', type:'横断オーケストレーター型',
    type_description:'複数領域を束ねて価値へ変える統合タイプ', tagline:'複数領域を束ねる力が、GitHubに残っている。',
    public_repo_count:26, evaluated_count:26, showcase_count:26, evidence_count:26, evidence_coverage:100,
    evidence_summary:{signatures:['GitHub Actions','Python package','FastAPI/Python API','Node package','React'],strong_architecture_repos:9,repos_with_tests:13,repos_with_ci:10},
    main_languages:'Python / HTML', latest_at:'2026-08-23T00:00:00Z',
    recommended:[
      {name:'rts-video-flow',reason:'構造Evidenceが強い・test/CIあり'},
      {name:'RTS',reason:'構造Evidenceが強い・test/CIあり'},
      {name:'WebAI-Bridge',reason:'構造Evidenceが強い・test/CIあり'}
    ],
    curiosity:['構造Evidence上、さらに掘る価値が高いrepoがあります','実ファイル構造から5種類以上の技術シグナルが見えます','test/CI Evidenceがあるrepoを13件確認しました'],
    detail:{
      axes:[['活動量',100],['技術横断',80],['Evidence量',90],['公開適性',100],['選択性',50],['継続性',100]],
      language_shares:[{name:'Python',value:35},{name:'HTML',value:15},{name:'JavaScript',value:4}],
      activity:[['最近90日以内',26,26],['評価対象repo',26,26],['公開候補repo',26,26]], activity_label:'高アクティブ',
      recommended:[
        {name:'rts-video-flow',reason:'構造Evidenceが強い・test/CIあり',language:'Python',updated_at:'2026-08-13T00:00:00Z'},
        {name:'RTS',reason:'構造Evidenceが強い・test/CIあり',language:'Python',updated_at:'2026-08-21T00:00:00Z'},
        {name:'WebAI-Bridge',reason:'構造Evidenceが強い・test/CIあり',language:'Python',updated_at:'2026-08-21T00:00:00Z'}
      ],
      traits:[['活動継続',100],['技術横断',80],['公開選別',100],['Evidence蓄積',90]],
      strengths:['複数技術をまたいで構成できる','継続して実装を前へ進める力がある','作ったものをEvidenceとして蓄積している'],
      growth:['構造Evidence上、さらに掘る価値が高いrepoがあります','実ファイル構造から5種類以上の技術シグナルが見えます','test/CI Evidenceがあるrepoを13件確認しました'],
      evidence:{analyzed_repos:26,evaluated_repos:26,coverage:100,signatures:['GitHub Actions','Python package','FastAPI/Python API','Node package','React'],repos_with_tests:13,repos_with_ci:10,strong_architecture_repos:9}
    }
  };
}
