import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {
  REPORT_SCHEMA,
  buildDeveloperCardReportV1,
  encodePublicReport,
  decodePublicReport,
  buildPublicReportUrl,
  buildMachineReportUrl,
  serializeMachineReport,
  readPublicReportFromLocation
} from '../src/public-report.mjs';

test('DeveloperCardReport v1 is canonical, public-safe and machine-readable', () => {
  const payload = {
    v:1,
    handle:'アルティメット',
    type:'システム構築型',
    recommended:[{name:'public-one',reason:'showcase'}],
    detail:{
      axes:[['活動量',80]],
      recommended:[{name:'public-one',reason:'showcase'},{name:'hidden-one',reason:'must not leak'}]
    },
    excluded_repo_names:['secret-repo'],
    arbitrary_private_field:'never serialize me'
  };
  const report = buildDeveloperCardReportV1(payload);
  assert.equal(report.schema, REPORT_SCHEMA);
  assert.equal(report.schema_version, 1);
  assert.equal(report.public_safe, true);
  assert.equal(report.evidence_scope, 'public-safe-aggregate');
  assert.equal(report.detail.recommended.length, 1);
  assert.equal(report.detail.recommended[0].name, 'public-one');
  assert.equal('excluded_repo_names' in report, false);
  assert.equal('arbitrary_private_field' in report, false);

  const token = encodePublicReport(payload);
  assert.deepEqual(decodePublicReport(token), report);
  assert.deepEqual(JSON.parse(serializeMachineReport(payload)), report);
});

test('new report URLs use query transport and legacy hash URLs remain readable', () => {
  const payload = {v:1,handle:'アルティメット',type:'システム構築型',recommended:[],detail:{}};
  const human = new URL(buildPublicReportUrl(payload, 'https://example.com/Developer-Card/?old=1#x'));
  assert.ok(human.searchParams.get('report'));
  assert.equal(human.searchParams.get('old'), null);
  assert.equal(human.hash, '');
  assert.equal(human.searchParams.get('view'), null);

  const machine = new URL(buildMachineReportUrl(payload, 'https://example.com/Developer-Card/'));
  assert.ok(machine.searchParams.get('report'));
  assert.equal(machine.searchParams.get('view'), 'json');

  const token = encodePublicReport(payload);
  const legacy = readPublicReportFromLocation({search:'',hash:`#report=${token}`});
  assert.equal(legacy.handle, 'アルティメット');
});

test('canonical X-card preview and PNG export use the same renderer contract', async () => {
  const app = await readFile(new URL('../src/app.mjs', import.meta.url), 'utf8');
  const share = await readFile(new URL('../src/share-card.mjs', import.meta.url), 'utf8');
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  assert.match(app, /renderShareCardDom\(lastCardModel\)/);
  assert.match(app, /exportShareCardPng\(lastCardModel\)/);
  assert.doesNotMatch(app, /function renderPngCard/);
  assert.match(share, /GitHub解析でわかる/);
  assert.match(share, /開発スタイル診断/);
  assert.match(share, /詳細レポートはこちら/);
  assert.match(html, /id="detailQr"/);
});

test('QR is generated by browser-compatible runtime instead of DETAIL placeholder', async () => {
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  const share = await readFile(new URL('../src/share-card.mjs', import.meta.url), 'utf8');
  assert.match(html, /qrcodejs\/1\.0\.0\/qrcode\.min\.js/);
  assert.match(share, /globalThis\.QRCode/);
  assert.match(share, /toDataURL\('image\/png'\)/);
  assert.doesNotMatch(share, /svgFallback\('DETAIL'\)/);
});

test('share and machine actions have separate responsibilities', async () => {
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  const app = await readFile(new URL('../src/app.mjs', import.meta.url), 'utf8');
  assert.match(html, /id="download">Xカードを保存/);
  assert.match(html, /id="share">投稿文をコピー/);
  assert.match(html, /id="machineDownload">JSONレポートを保存/);
  assert.match(html, /id="machineCopy">Machine URLをコピー/);
  assert.match(app, /navigator\.canShare\?\.\(\{files:\[file\]\}\)/);
  assert.match(app, /copyText\(text\)/);
  assert.match(app, /serializeMachineReport\(lastCardModel\.publicPayload\)/);
  assert.match(app, /copyText\(lastCardModel\.machine_url\)/);
});

test('machine view renders canonical JSON after browser-side decode', async () => {
  const detail = await readFile(new URL('../src/detail-report.mjs', import.meta.url), 'utf8');
  assert.match(detail, /isMachineReportLocation\(\)/);
  assert.match(detail, /id="machineReport"/);
  assert.match(detail, /serializeMachineReport\(payload\)/);
});

test('avatar preprocessing can remove only edge-connected light backgrounds', async () => {
  const guard = await readFile(new URL('../src/mobile-memory-guard.mjs', import.meta.url), 'utf8');
  assert.match(guard, /removeConnectedLightBackground/);
  assert.match(guard, /lightBorder\/border<0\.55/);
  assert.match(guard, /d\[p\+3\]=0/);
});
